[build]
  base = "frontend-react"    # FIX Ya está en el directorio frontend-react
  command = "npm run build"  # No necesitamos cd
  publish = "build"          # El build se generará aquí

[functions]
  directory = "../netlify/functions"  # Ruta relativa desde frontend-react
  external_node_modules = ["mysql2"]
  included_files = ["../netlify/functions/**"]
  node_bundler = "esbuild"

[dev]
  command = "npm start"    # Simplificado
  targetPort = 3000       
  port = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200