[build]
  command = "cd frontend-react && npm run build"
  publish = "frontend-react/build"
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/functions/**"]
  external_node_modules = ["mysql2"]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  command = "npm --prefix frontend-react start"
  targetPort = 3000
  port = 8888
  functionsPort = 9999

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200